#!/usr/bin/env python

import os
import rospy
import sys
import time

from rosshow.ImuViewer import ImuViewer
from sensor_msgs.msg import Imu

from rosshow.NavSatFixViewer import NavSatFixViewer
from sensor_msgs.msg import NavSatFix

from rosshow.PointCloud2Viewer import PointCloud2Viewer
from sensor_msgs.msg import PointCloud2

from rosshow.ImageViewer import ImageViewer
from sensor_msgs.msg import Image

if __name__ == "__main__":
    if len(sys.argv) <= 1:
        print("Usage: rosshow <topic>")
        sys.exit(0)

    TOPIC = sys.argv[1]
    topics = dict(rospy.get_published_topics())
    if TOPIC not in topics:
        print("Topic {0} does not appear to be published yet.".format(TOPIC))
        sys.exit(0)

    rospy.init_node('rosshow')

    if topics[TOPIC] == 'sensor_msgs/PointCloud2':
        viewer = PointCloud2Viewer()
        rospy.Subscriber(TOPIC, PointCloud2, viewer.update)
        rospy.spin()

    elif topics[TOPIC] == 'sensor_msgs/Imu':
        viewer = ImuViewer()
        rospy.Subscriber(TOPIC, Imu, viewer.update)
        rospy.spin()

    elif topics[TOPIC] == 'sensor_msgs/NavSatFix':
        viewer = NavSatFixViewer()
        rospy.Subscriber(TOPIC, NavSatFix, viewer.update)
        rospy.spin()

    elif topics[TOPIC] == 'sensor_msgs/Image':
        viewer = ImageViewer()
        rospy.Subscriber(TOPIC, Image, viewer.update)
        rospy.spin()

    else:
        print("Topic type not supported")
